"""Added task log table

Revision ID: 982277d032ef
Revises: b5d35571e97f
Create Date: 2023-11-27 18:17:39.902710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982277d032ef'
down_revision = 'b5d35571e97f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_log')
    # ### end Alembic commands ###
