"""project added to the task

Revision ID: b5d35571e97f
Revises: ef4bd02c14e3
Create Date: 2023-08-20 14:12:23.052626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5d35571e97f'
down_revision = 'ef4bd02c14e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'project_id')
    # ### end Alembic commands ###
